---
apiversion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: task
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              services:
                name: nodejs
                port:
                  number: 3000
