apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodejs
  namespace: task
spec:
  serviceName: nodejs
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: arunachalamg/nodejs:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-config
            - secretRef:
                name: mysql-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: nodejs-volume
              mountPath: /usr/src/application
      volumes:
        - name: nodejs-volume
          persistentVolumeClaim:
            claimName: nodejs-pvc

