apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: task
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

